#!/usr/bin/env python
#post-receive

import sys
import os
import subprocess

def get_current_repo_name():
    cur_path = os.getcwd()
    print("cur path {:s}".format(cur_path))

# refs = sys.stdin.read().split()

get_current_repo_name()

