#!/usr/bin/env python
#post-receive

import sys
import os
import subprocess

def get_current_repo_name():
    cur_repo = os.path.basename(os.getcwd())
    sys.stdout.write("Current repo({:s}) was added for tag_checker update list".format(cur_repo))
    sys.stdout.flush()

# refs = sys.stdin.read().split()

get_current_repo_name()

